<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8e835f38146f864f573669e1cebc264f
{
    public static $files = array (
        'cb4aeec40c9362b2025b90928aafeab3' => __DIR__ . '/../..' . '/index.php',
    );

    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'CoffeeCode\\Uploader\\' => 20,
        ),
        'A' => 
        array (
            'Assets\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'CoffeeCode\\Uploader\\' => 
        array (
            0 => __DIR__ . '/..' . '/coffeecode/uploader/src',
        ),
        'Assets\\' => 
        array (
            0 => 'C:\\xampp\\htdocs\\financeiro\\assets',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8e835f38146f864f573669e1cebc264f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8e835f38146f864f573669e1cebc264f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8e835f38146f864f573669e1cebc264f::$classMap;

        }, null, ClassLoader::class);
    }
}
